[package]
org = "ballerina"
name = "protobuf"
version = "1.5.0"
authors = ["Ballerina"]
keywords = ["wrappers"]
repository = "https://github.com/ballerina-platform/module-ballerina-protobuf"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"
export = ["protobuf", "protobuf.types.any", "protobuf.types.duration", "protobuf.types.empty", "protobuf.types.struct", "protobuf.types.timestamp", "protobuf.types.wrappers"]

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "protobuf-native"
version = "1.5.0"
path = "../native/build/libs/protobuf-native-1.5.0.jar"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.20.3.jar"
