[package]
org = "ballerina"
name = "protobuf"
version = "1.6.1"
authors = ["Ballerina"]
keywords = ["wrappers"]
repository = "https://github.com/ballerina-platform/module-ballerina-protobuf"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"
export = ["protobuf", "protobuf.types.any", "protobuf.types.duration", "protobuf.types.empty", "protobuf.types.struct", "protobuf.types.timestamp", "protobuf.types.wrappers"]

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "protobuf-native"
version = "1.6.1"
path = "../native/build/libs/protobuf-native-1.6.1.jar"

[[platform.java17.dependency]]
path = "./lib/protobuf-java-3.25.5.jar"
